### ISSUE TITLE
cannot get this to work after getting it to work the first time

### ISSUE THREAD

**Issue by Vaslo** [rauenzi/Trilium-MarkdownPreview#4]
I've followed and re-read the directions a bunch of times.  Basically I:
- Download the latest version to my drive.
- Under root I right click and do "import into note"
- I get a new note on the left called "Trilium-MarkdownPreview-main" with a bunch of notes, code, etc
- I open a new note (tried this as both a child and on it's own"
- I make it markdown (I didn't need to do this the first time and it still worked"
- I type #markdownPreview at the top of the note

Nothing happens.   Is there a step I'm missing or some issue that I am not considering?  Thanks!

**Comment by zerebos** [comment]
> I type #markdownPreview at the top of the note

This should be an attribute, not just in the note

**Comment by Vaslo** [comment]
Thanks for the reponse.  I have tried in earnest to understand what you are telling me by doing some searches online and skimming youtube videos but I don't understand how to get this working.  I went to "Owned Attributes" and tried #markdownPreview, #widget = #markdownPreview, I tried putting #widget in the original download, none of this is working and it isn't super clear to a Trilium Novice how to do widgets.  Can you be a little more specific?  For now, I have the zip file imported and it's its own note on the left.  I assumed I could make notes anywhere and then somehow pass the markdownPreview to it.  Thanks for helping me through.

**Comment by zerebos** [comment]
When you imported the widget did you uncheck "Safe Import"?

The note you want to preview should have Owned Attributes like this:

![image](https://github.com/user-attachments/assets/f613bef8-693b-47a8-a0c2-74153d8e3c94)

**Comment by Vaslo** [comment]
Ok finally got it working with your instructions plus for anyone else who sees this, you have to shutoff uBlockOrigin for your VPS or it looks like it blocks the JavaScript.   Can confirm as of today it works well in Edge.  Thanks for your patience and quick responses - I'd love to see the new maintainers incorporate your good work here into the base program.

**Comment by 624939655** [comment]
@zerebos 
I used the desktop app and imported the plugin as you provided, setting the own attribute to #markdownPreview in the new note

But the preview did not take effect

<img width="617" alt="Image" src="https://github.com/user-attachments/assets/ae5204e6-cfba-4e57-8070-fc81ecf8b3b1" />

<img width="795" alt="Image" src="https://github.com/user-attachments/assets/86a9fae1-88cc-4b3b-8525-969647901a78" />

<img width="587" alt="Image" src="https://github.com/user-attachments/assets/9be335c7-08b4-476f-b4f0-066384430c39" />

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/b335d347-b1d0-43fb-91a5-88b2bca493f6" />


Is there a video explaining how to import and use it
